### ISSUE TITLE
Sorting: Notes do not update sort order

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-macos#102]
When set to order notes by date modified the order the notes are displayed does not change when a note is modified. You have to either resort the notes or relaunch the app to get the new order.

The same thing happens in the web app as well.

As a note is modified it should move the appropriate position in the list of notes based on the sort order.

**Comment by jtoy** [comment]
I am experiencing this exact same issue all of a sudden. What is happening? Here is an example of it:
https://cl.ly/3Y1M0k400r1O
I am on version 1.3.1

**Comment by edequalsawesome** [comment]
Also referenced in #1803620-zen

**Comment by rachelmcr** [comment]
I just noticed this while using version 1.10.0 beta.

**Comment by rezzap** [comment]
> changing folders does update by modified but that’s not a workflow that’s expected nor useful. If it is to sort by modified then it should sort by modified. ... Bringing a real-time modified sorting like the mobile app would much more useful.

From 2999927-zen

**Comment by codebykat** [comment]
I just noticed this on Simplenote 2.0 while testing alphabetical sorting. If you sort notes alphabetically, then change the title of a note from e.g. "aaaaa" to "zzzzz", it stays in the same place in the list instead of getting dynamically resorted. It doesn't get resorted until you either quit and relaunch the app or change the sort order setting and then change it back.
