### ISSUE TITLE
Words at the edge are slightly cut off

### ISSUE THREAD

**Issue by gupta-anmol** [Automattic/simplenote-macos#1048]
Letters from words on the right edge of the editor get cut off.

### Expected

Edge words should not be cut off. If they are a little too big, they should just move to the next line.

### Observed

If I have text inside a note spanning multiple lines, once in a while there are words that get cut-off a little from the end. Resizing the text size or the window doesn't help either.

### Reproduced

Add multiple lines of text and observe the words on the right edge get cut-off. Try resizing the window to see different words get cut-off.

### Screenshot and video

![image](https://user-images.githubusercontent.com/44764339/135719331-8cad7465-f91d-43b9-8319-a5628f7e1a04.png)

https://user-images.githubusercontent.com/44764339/135719184-855a9720-e7d3-4587-b957-e4fb28e66cb9.mov

I am using Simplenote 2.15.1 on macOS Big Sur Version 11.5

**Comment by pachlava** [comment]
Thank you for the report @gupta-anmol ! We already track this under #910. I will close your issue because of this, and will mention it in #910.

While it's not fixed, there's a workaround you can use: opening `General` macOS Preferences and setting `Show scroll bars` to `When scrolling`. While this might be not the most suitable solution, it's there.
