### ISSUE TITLE
simplenote-macos does not work behind a proxy

### ISSUE THREAD

**Issue by nighthawk469** [Automattic/simplenote-macos#1183]
When I am behind my company network proxy, simplenote-macos does not sync or download notes to the server. 

In my macOS Network settings, Proxies, I have a proxy defined in "Automatic proxy configuration". 

Other apps like OneNote and UpNote have no problem syncing the notes to the server behind the network proxy.

Similar to this issue
https://github.com/Automattic/simplenote-macos/issues/86

Make|Model|macOS Version|App Version
-|-|-|-
-|-|MacOS 14.5|Simplenote 2.20

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by charliescheer** [comment]
Hello @nighthawk469 Thanks for reporting.  In the issue that you linked to #86 there were some steps to try and see if you can connect to simplenote while on your proxy.  Have you tried those steps?

As was mentioned in that issue Simplenote Mac does work while on a proxy, but if your proxy servers do not allow access to `api.simplenote.com` then Simplenote wont be able to sync because the network traffic is being blocked by the proxy servers.  If that is the case you will need to have the following URLs whitelisted

```
https://api.simperium.com
https://auth.simperium.com/1/
```

Please see the previous issue for more details on this issue

**Comment by nighthawk469** [comment]
@charliescheer ok you are correct 

When I try to access https://auth.simperium.com/1/ on my company network with a proxy, i get "404 not found
