### ISSUE TITLE
Deleting a Tag Hides Drop Down Arrow

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#153]
After deleting a tag, the down arrow doesn’t reappear next to my remaining tags (to rename/delete another tag) although I can still right-click to rename/delete tags:

![simplenotetags](https://user-images.githubusercontent.com/789137/33843123-5920bcb0-de51-11e7-824d-4aba998614a5.gif)

**Comment by roundhill** [comment]
So far I haven't been able to reproduce this one.

**Comment by jaymendoza** [comment]
User experiencing the issue here: 946422-zen

I'm able to reproduce it. After deleting the first tag, the arrow disappears. Delete menu option is still available via the right-click context menu. Regardless of how the first tag is deleted (via the arrow or via the context menu), further deletions won't work until the app is restarted.

For me, it's reproducible on Version 1.2 (1200).

**Comment by jleandroperez** [comment]
Closing this one since, as per Spring Cleaning, the arrows are gone.

Thanks everyone!!
Ref. #458
