### ISSUE TITLE
Markdown Checkbox list not displayed as checkboxes in markdown preview

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-macos#277]
#### Steps to reproduce
1. start a new note
2. Make sure markdown is enabled
3. type:
```
- [ ] Test 1
- [ ] Test 2
- [x] Test 3
```
4. switch to preview mode

#### What I expected
Expected the markdown to be parsed into a list of checkboxes, with the last one checked like this:
<img src="https://user-images.githubusercontent.com/5810477/49703026-e98d0200-fbcd-11e8-89ed-e4492d1a510c.png" width="350"/>

#### What happened instead
<img src="https://user-images.githubusercontent.com/5810477/49703035-f01b7980-fbcd-11e8-9904-90e99b3993ef.png" width="350"/>

#### Simplenote version
1.3.9

#### macOS version
10.14.1

**Comment by Tav0** [comment]
+1 big issue right now when I create a checklist in a non-markdown formatted note and then switch to markdown formatted, the checklist display is gone.

**Comment by jleandroperez** [comment]
Closing as cannot repro anymore. (The Markdown processing lib got several updates along the way).

Simplenote 1.9 / macOS Catalina.

Thank you Amanda + everyone!!

**Comment by edgarklein** [comment]
I am currently on version 6.7.3 and with MacOS Monterey (12.6) with M1 chip and I cannot add a checkbox no matter what.

Also if I add a bullet point using * and then another few more points. If I delete the first point and try to re-add, it will just display the * character instead of the bullet point. After restarting UpNote, it's working again.
