### ISSUE TITLE
Checklist icons disappear when markdown is toggled

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#343]
### Expected
1. Added checklist items to a note
2. Turned markdown on (or off)
3. Expected the checklist icons to stay

### Observed
Instead, the icons disappeared

![checklists](https://user-images.githubusercontent.com/31680407/60216849-29010000-9839-11e9-9e61-e9fd497e0f65.gif)

Seems related to these issues: #321 #309 #307 

Make|Model|macOS Version|App Version
-|-|-|-
Apple | MacBook Pro | 10.14.5 | 1.4.2

**Comment by Robertght** [comment]
+1  - Requested by a user.

**Comment by charliescheer** [comment]
I did some testing on this and the checklists are removed when ever the note is rerendered and not just with enabling or disabling markdown.

If you check out this gif, the same thing occurs when I zoom in or out on Simplenote 

<img src="https://cdn-std.droplr.net/files/acc_593859/Z0dz2E" />

It looks like Simplenote still sees them as checklists because a carriage return will create a new check box, but they aren't displayed anymore.
