### ISSUE TITLE
cmd+f to focus search field?

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#36]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Tuesday Feb 17, 2015 at 20:07 GMT_

---

User suggestion: 

`Hitting cmd+f should focus on the search field`

**Comment by bummytime** [comment]
Currently `⌘ + ⌥ + F` brings up note search, `⌘ + F` does in-note search.  

> If it's found, the dialog disappears,and the matching text is selected. Pressing enter, which in almost all other programs with search will find the next instance, instead wipes out the text I was looking for and replaces it with a carriage return.

We should probably look into this.

**Comment by jleandroperez** [comment]
As Bummy detailed:

**CMD + F**: Search within the document
**CMD + Option + F**: Toggle the SearchBar as the first responder

This matches the shortcuts detailed in [simplenote.com/help](https://simplenote.com/help/)

I'm closing this one, since AAPL Notes has the exact same shortcuts, and doing something else might be confusing to new users.

Please feel free to reopen if needed. Thanks everyone!!
