### ISSUE TITLE
Question: Project Build Unsuccessful

### ISSUE THREAD

**Issue by kedar9** [Automattic/simplenote-macos#679]
Hi 👋 
I am new to MacOS development. Apologies for the basic question, but I could not find this information in the readme.

I cloned the repo and installed ruby (`rvm install ruby-2.5.5`) and installed dependencies (`rake dependencies`).
But, trying to Run **Simplenote.xcworkspace** (in Xcode), keeps throwing a "Build Failed" message.

Am I missing something? How do I successfully run it?
Thanks.

**Comment by jleandroperez** [comment]
Hi there @kedar9,

I'm not sure what's the exact error you're getting (please copy + paste the full text!), but you're also gonna need to setup Codesign to run the app.

Setting up Xcode for Codesign, pretty much, involves:
1. Creating an Apple Developer Account at https://developer.apple.com
2. Launch Xcode
3. Open: **Xcode > Preferences > Accounts**
4. Sign into your account

And then you're also probably gonna need to change few things in the Xcode project itself, so that it runs on your own Developer Account. Essentially you'd need to pick your `Personal Developer Account` as the Team, in the Simplenote Target, as seen in this screenshot:

<img width="300" alt="Team" src="https://user-images.githubusercontent.com/1195260/94455325-4e419400-0189-11eb-9d8a-0104864e01f7.png">

Hope that helps!

**Comment by jleandroperez** [comment]
Closing this one for the time being. Please feel free to reopen if needed, happy to help with anything!!

And thank you for your interest in Simplenote!! 😄
