### ISSUE TITLE
Why is a dedicated MacOS app if an Electron app is also being maintained

### ISSUE THREAD

**Issue by baer** [Automattic/simplenote-macos#81]
I was looking at Simplenote this morning and noticed that the MacOS and the Electron projects are completely separate. Baring a few small exceptions an Electron app can do everything that a native app can. Given the high cost of maintenance and of simultaneously developing features in multiple projects I wanted to ask: What is the reason for having two separate projects as opposed to doubling down on one?

Thanks for all the awesome work you've done to create this product and to foster OSS tech for so long. You are leaders in our community!

**Comment by jleandroperez** [comment]
Hello @baer,

Thanks for your interest in Simplenote!. One of the main reasons why we currently have both, macOS and Electron apps, is because the former one was built first, and has been around for quite some, time: it's solid rock.

On the other side, the Electron app is the new kid in the block. We might, down the path, deprecate the native version, and maintain just one. (Undefined / undecided for the time being).

Again, thank you for writing us!!,
Have an awesome day,

Jorge

**Comment by baer** [comment]
That's what I figured the answer was. Thanks for all the great work and for documenting this. Hopefully this can be a reference for anybody looking to contribute in the future.

**Comment by hisyam** [comment]
Electron apps are usually slow to open, even with SSD.
