### ISSUE TITLE
Is electron in the works for mac app?

### ISSUE THREAD

**Issue by titoesteves** [Automattic/simplenote-macos#84]
Just curious if electron is in the works for the mac application? If so, any eta? If not, I'd like to add this as a feature request. This would provide many benefits. Two near to my heart. Javascript developers can contribute. And markdown support

**Comment by jleandroperez** [comment]
@titoesteves we're not really looking into replacing the native macOS app with an electron version, at least not for the time being.

Nevertheless, since the Electron app is opensource, you're absolutely free to check out the project / submit a pull request to make it work in any other platform. I'm not sure if we'd replace the AppStore binary with a hybrid, but still, i'm pretty sure macOS support wouldn't require a huge modification.

On the other hand, the Mac project also supports the new Swift language. It's syntax similar to JS, you'd absolutely love it

Thanks for your interest in Simplenote!
